Bumped MySQL and Sqlite Deps
rahmanfadhil/cotton pull request #28
Opened 2020-11-20 00:32 UTC by atsjj

* MySQL has been bumped to address the `v` prefix deprecation bug.
* Sqlite has been bumped to take advantages upstream, see dyedgreen/deno-sqlite#94
  and dyedgreen/deno-sqlite#91.
* Bumped Dockerfile deno base from `1.4.4` to `1.5.2`, which is the latest available
  container at the time of this PR.

2020-11-20 00:35 UTC, atsjj commented
Hello!

I was wanting to try out this project and I ran into some snags. I'm using my fork to get by in the meantime, but I wanted to offer the PR.

Thanks for the project!

2020-11-20 12:44 UTC, rahmanfadhil requested changes
Hi, thank you so much! 😃

I recently merged another PR, and apparently, it generates a conflict in `deps.ts`. Can you please solve it first before I can merge it? Thanks!

2020-11-20 14:00 UTC, atsjj commented
I rebased my PR for you and resolved the conflict.

2020-11-21 03:25 UTC, rahmanfadhil approved these changes
Thank you so much! 😃

2020-11-21 03:26 UTC, merged